name: terraform-deploy-dev
description: terraform-dev
on:
  workflow_call:
inputs:
  tag: # id of input
    description: 'Tag of the master branch'
    required: false
    default: ''
    type: string

runs:
  using: "composite"

  steps:
    - name: Branch Check
      run: |
        echo "${{ inputs.tag }}"
      shell: bash

    - name: Terraform Init
      id: init
      run: |
        cd src
        terraform init
      shell: bash


    # Generates an execution plan for Terraform
    - name: Terraform Plan with env
      id: plan
      run: |
        cd src
        terraform plan
      shell: bash
