name: terraform-deploy-dev

on:
  workflow_call:
inputs:
  tag: # id of input
    description: 'Tag of the master branch'
    required: false
    default: ''
    type: string

runs:
  using: "composite"
  steps:
    - name: Branch Check
      run: |
        echo "${{ inputs.tag }}"
      shell: bash
