name: terraform-deploy-dev
description: terraform-dev
on:
  workflow_call:
inputs:
  tag: # id of input
    description: 'Tag of the master branch'
    required: false
    default: ''
    type: string

  repo: # id of input
    description: 'Tag of the master branch'
    required: false
    default: ''
    type: string

runs:
  using: "composite"

  steps:
    - name: Branch Check
      run: |
        echo "${{ inputs.tag }}"
      shell: bash

#    - name: Repo from config
#      id: repo-check
#      run: |
#        cd config
#        repos=$(grep -A3 'repo:' config.yml | tail -n1 | awk '{ print $2}')
#        echo "repo=$repos" >> $GITHUB_OUTPUT
#      shell: bash

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: Djackk
        path: './gitHub-actions'

    - name: Terraform Init
      id: init
      run: |
        cd src
        terraform init
      shell: bash


    # Generates an execution plan for Terraform
    - name: Terraform Plan with env
      id: plan
      run: |
        cd src
        terraform plan
      shell: bash
