terraform:
  version: 1.0.1
  destination_base_branch: main
  user_email: siddom91@gmail.com
  user_name: Djackk
  source_folder: terraform
  github_repo: Djackk
  repo:
    - Djack/gitHub-actions
    - Djack/github-workflows
