terraform:
  version: 1.0.1
  destination_base_branch: master
  user_email: siddharth.jumani@takeoff.com
  user_name: Siddharth-Jumani
  org_name: TakeoffTech
  repo:
    - gitHub-actions
    - github-workflows
