name: terraform-deploy-dev
description: terraform-dev
on:
  workflow_call:
inputs:
  tag: # id of input
    description: 'Tag of the master branch'
    required: false
    default: ''
    type: string

  rep: # name of the repo
    description: 'Name of the repo from config file'
    required: false
    default: ''
    type: string

runs:
  using: "composite"

  steps:
    - name: Tag & Repo Check
      run: |
        echo "Code is being deployed from the tag: ${{ inputs.tag }}"
        echo "Code is being deployed from the repo: ${{ inputs.rep }}"
      shell: bash

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.rep }}

    - name: Terraform Init
      id: init
      run: |
        cd src
        terraform init
      shell: bash

    # Generates an execution plan for Terraform
    - name: Terraform Plan with env
      id: plan
      run: |
        cd src
        terraform plan
      shell: bash
