name: deploy-terraform-workflow

on:
  workflow_dispatch:
jobs:
  deployment_Status:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Check Failed
        if: github.ref_type != 'tag'
        run: |
          echo "Please select a tag for the deployment : ${{ github.head_ref || github.ref_name }}"
#          exit 1
      - name: Deployment Check Passed
        if: github.ref_type == 'tag'
        run: |
          echo "Code will be deployed from the tag ${{ github.ref }}"

  extract_config:
    needs:
      - deployment_Status
    runs-on: ubuntu-latest
    steps:
      - name: Install yq
        run: |
          sudo snap install yq

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}

      - name: Extract org name from config
        id: extract-org-name
        run: |
          org_name=$(yq eval .terraform.org_name configs/terraform.yml)
          echo "org_name=$org_name" >> $GITHUB_OUTPUT
        shell: bash

      - name: Extract repos from config
        id: extract-repos
        run: |
          org=${{steps.extract-org-name.outputs.org_name}}
          targets=($(yq eval .terraform.repo configs/terraform.yml | awk '{print $2}'))
          for target in ${targets[@]};do
            repos+="\"$org/$target\","
          done
          echo "target_matrix=["$(echo "${repos%?}")"]" >> $GITHUB_OUTPUT
        shell: bash

      - name: Extract user email from config
        id: extract-email
        run: |
          email=$(yq eval .terraform.user_email configs/terraform.yml)
          echo "user_email=$email" >> $GITHUB_OUTPUT
        shell: bash

      - name: Extract user name from config
        id: extract-name
        run: |
          name=$(yq eval .terraform.user_name configs/terraform.yml)
          echo "user_name=$name" >> $GITHUB_OUTPUT
        shell: bash

      - name: Extract destination base branch from config
        id: extract-dest-base
        run: |
          base=$(yq eval .terraform.destination_base_branch configs/terraform.yml)
          echo "dest_base=$base" >> $GITHUB_OUTPUT
        shell: bash

    outputs:
      target_matrix: ${{ steps.extract-repos.outputs.target_matrix }}
      user_email: ${{ steps.extract-email.outputs.user_email }}
      user_name: ${{ steps.extract-name.outputs.user_name }}
      dest_base: ${{ steps.extract-dest-base.outputs.dest_base }}

  automated_pr:
    needs:
      - extract_config
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:  ${{fromJson(needs.extract_config.outputs.target_matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}

      - name: Create pull request
        uses: Djackk/action-pull-request-another-repo@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TEST_SECRET }}
        with:
          source_folder: 'terraform/*.yml'
          destination_repo: ${{ matrix.target }}
          destination_folder: '.github/workflows'
          destination_base_branch: ${{ needs.extract_config.outputs.dest_base }}
          destination_head_branch: 'CI-CD_WORKFLOWS'
          user_email: ${{ needs.extract_config.outputs.dest_base }}
          user_name: ${{ needs.extract_config.outputs.dest_base }}
