name: deploy

on:
  workflow_dispatch:
    inputs:

jobs:
  Deployment_Status:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Check Failed
        if: github.ref_type != 'tag'
        run: |
          echo "Please select a tag for the deployment"
#          exit 1
      - name: Deployment Check Passed
        if: github.ref_type == 'tag'
        run: |
          echo "Code will be deployed from the tag ${{ github.ref }}"

  Config-update:
    needs:
      - Deployment_Status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}

      - name: Repo from config
        id: repo-check
        run: |
          cd config
          repos=$(grep -A3 'repo:' config.yml | tail -n1 | awk '{ print $2}')
          echo $repos
          echo "repo=$repos" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create pull request
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.TEST_SECRET }}
        working-directory: ./terraform
        with:
          source_folder: ''
          destination_repo: ${{steps.repo-check.outputs.repo}}
          destination_folder: '.github/workflows'
          destination_base_branch: 'main'
          destination_head_branch: 'automated-pr'
          user_email: 'siddom91@gmail.com'
          user_name: 'Djackk'
    outputs:
      repository: ${{ steps.repo-check.outputs.repo }}

#  terraform:
#    needs:
#      - Config-update
#    runs-on: ubuntu-latest
#    env:
#      GOOGLE_CLOUD_PROJECT: sandbox-20220909-4sfsll
#    environment: production
#
#    defaults:
#      run:
#        shell: bash
#
#    permissions:
#      contents: 'read'

#    steps:
#    - name: terraform-deploy-dev
#      uses: Djackk/gitHub-workflows/terraform@main
#      with:
#        tag: ${{ github.ref_name }}
#        rep: ${{ needs.Config-update.outputs.repository }}

