name: Release (Manual)

on:
  workflow_call:
    inputs:
      tag: # id of input
        description: 'Tag of the master branch'
        required: false
        default: ''
        type: string

jobs:
  Manual-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Environment Check
        run: |
          echo "The code will be deployed to : ${{ inputs.Environment }} Environment"
      - name: Region Check
        run: |
          echo "${{ github.event.inputs.Region }}"
      - name: Branch Check
        run: |
          echo "${{ inputs.branch }}"
      - run: echo "🍏 This job's status is ${{ job.status }}."
