name: Call a reusable workflow for Dev

on:
  workflow_dispatch:
    inputs:

jobs:
  Deployment_Status:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Check Failed
        if: github.ref_type != 'tag'
        run: |
          echo "Please select a tag for the deployment"
          exit 1
      - name: Deployment Check Passed
        if: github.ref_type == 'tag'
        run: |
          echo "Code will be deployed from the tag ${{ github.ref }}"

  Call-Release:
    needs:
      - Deployment_Status
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLOUD_PROJECT: sandbox-20220909-4sfsll
    environment: production

    defaults:
      run:
        shell: bash

    permissions:
      contents: 'read'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/932079530572/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'auto-deploy-standard-svc@sandbox-20220909-4sfsll.iam.gserviceaccount.com'

      - name: terraform-deploy-dev
        uses: Djackk/gitHub-workflows/terraform@main
        with:
          tag: ${{ github.ref_name }}

